## Numpy_Basics_4

--> Broadcasting  
--> Mean  
--> Comparison Operators Universal Functions  
--> Counting entries  
--> Boolean Operators  
--> Boolean Array as Masks  
--> Fancy Indexing  
--> Combined Indexing  
--> Modifying Values using Fancy Indexing  
--> at()  


### Broadcasting 

In [2]:
import numpy as np

In [11]:
# Broadcasting -
# Broadcasting automatically adjusts arrays with smaller dimensions to match the shape of larger arrays
# The 1D array is "stretched" across the rows to match its shape

a = np.array([1,2,3,4])
b = np.array([4,3,2,6])

In [4]:
print('Result -',a+b)


Result - [ 5  5  5 10]


In [5]:
print('Result -',a+3)

Result - [4 5 6 7]


In [10]:
c = np.ones((4,4))
print('Values of c- \n',c,'\n')   # This gives a 4x4 array consisting of all 4's
print("Result -\n",a+c)  # Here 'a' is a 1D array which brodcasts or streches into array 'c' and gives the result 

Values of c- 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Result -
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


In [49]:
# Rules of Broadcasting

# Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side

# Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape

# Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised

In [19]:
# Dimensions are compatible if:
# They are the same, or one of the dimensions is 1.

# in the below case the column size 3 is matching 

a = np.array([1,2,3]) # shape(3,)
b = np.array([[1,2,3],[2,3,4]]) # shape(2,3)
a + b 

a- 
 [0 1 2] 

b- 
 [[0]
 [1]
 [2]] 

Shape of 'a' -  (3,) 

Shape of 'b' - (3, 1) 

Result of a + b 
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [44]:
a = np.array([1,2,3]) # shape(3,)
b = np.array([[1],[2],[3]]) #Shape (3,1)
print("Shape of 'a' ",a.shape,'\n')
a= a[:,np.newaxis]
print("Shape of 'a' after using newaxis -",a.shape,'\n')
print("Shape of 'b'-",b.shape,'\n')
print(a+b) # This satisfies the above condition given 
           # Dimensions are compatible if:
           # They are the same, or one of the dimensions is 1.

Shape of 'a'  (3,) 

Shape of 'a' after using newaxis - (3, 1) 

Shape of 'b'- (3, 1) 

[[2]
 [4]
 [6]]


In [46]:
a = np.array([1, 2, 3])  # Shape: (3,)
b = np.array([4, 5, 6])  # Shape: (3,)

print(a + b)  # Both shapes are identical, no broadcasting needed.


[5 7 9]


In [47]:
a = np.array([1, 2, 3])  # Shape: (3,)
b = 10  # Shape: () (scalar)

print(a+b)  # Scalar is broadcast to match the shape of 'a'.



[11 12 13]


### Mean

In [50]:
a = np.random.random((10,3))
print("Array \n",a)

Array 
 [[0.79922767 0.03134028 0.03150577]
 [0.35162198 0.10093931 0.69824031]
 [0.76471602 0.77496155 0.83974335]
 [0.30594325 0.96171716 0.47698395]
 [0.82452214 0.00638658 0.42840624]
 [0.35124004 0.38474404 0.46866608]
 [0.8958795  0.60541498 0.82165415]
 [0.32322405 0.24104336 0.7868113 ]
 [0.11477982 0.47051452 0.62972838]
 [0.4918082  0.2150976  0.29785493]]


In [56]:
print("mean -",np.mean(a)) # Gives the mean of the entire array 

mean - 0.4831572169771131


In [58]:
print("Mean of Columns -",a.mean(0),'\n') # Gives the mean of columns - 3 outputs 
print("Mean of Rows -",a.mean(1)) # Gives the mean of rows - 10 outputs 

Mean of Columns - [0.52229627 0.37921594 0.54795945] 

Mean of Rows - [0.28735791 0.38360053 0.79314031 0.58154812 0.41977165 0.40155006
 0.77431621 0.45035957 0.40500758 0.33492024]


In [60]:
# Centered_mean = Each_value - mean

a = np.array([1,2,3])
print("Array -\n ",a)            # creating a 1D array 

mean_a = a.mean()                # Produces mean of array 'a'
print("Mean of 'a'-",mean_a)

centered_mean_a = a - mean_a     # Produces the cenetered mean of each element
print("Centered Mean of 'a'- ",centered_mean_a)

Array -
  [1 2 3]
Mean of 'a'- 2.0
Centered Mean of 'a'-  [-1.  0.  1.]


In [65]:
# In this code we are finding the centered the array with respect to the overall mean

b = np.random.random((4,3))       # We are creating a 4x3 array 
print("array -\n",b)

mean_b = b.mean()                 # We are producing mean of the array 'b'
print("\nMean of 'b'-",mean_b)

centered_mean_b = b - mean_b      # This produces the centered mean of each element
print("\nCentered mean of 'b'- \n", centered_mean_b)

array -
 [[0.82173186 0.84070575 0.56655382]
 [0.10017947 0.96577366 0.8185708 ]
 [0.649112   0.55031315 0.33193935]
 [0.54871321 0.8460914  0.08037438]]

Mean of 'b'- 0.5933382373425805

Centered mean of 'b'- 
 [[ 0.22839363  0.24736751 -0.02678442]
 [-0.49315876  0.37243543  0.22523256]
 [ 0.05577376 -0.04302509 -0.26139889]
 [-0.04462503  0.25275316 -0.51296386]]


In [67]:
# In this code we are finding the mean along specific axes of a 2D array (b) and then center the array accordingly.

mean_columns_b = b.mean(axis=0)
print("Mean of columns of 'b'-\n",mean_columns_b)  # produces mean of the 3 columns 

centered_columns_b = b - mean_columns_b
print("\nCentered Columns of 'b' -\n",centered_columns_b) # Produces the central mean along columns

mean_rows_b = b.mean(axis=0)
print("\nMean of rows of b-\n",mean_rows_b) # Produces mean of the 4 rows 

centered_rows_b = b - mean_rows_b
print("\n Centered Rows of 'b'- \n",centered_rows_b) # Produces centered mean along rows 

Mean of columns of 'b'-
 [0.52993414 0.80072099 0.44935959]

Centered Columns of 'b' -
 [[ 0.29179773  0.03998476  0.11719423]
 [-0.42975466  0.16505268  0.36921121]
 [ 0.11917787 -0.25040784 -0.11742023]
 [ 0.01877907  0.04537041 -0.3689852 ]]
Mean of rows of b-
 [0.52993414 0.80072099 0.44935959]

 Centered Rows of 'b'- 
 [[ 0.29179773  0.03998476  0.11719423]
 [-0.42975466  0.16505268  0.36921121]
 [ 0.11917787 -0.25040784 -0.11742023]
 [ 0.01877907  0.04537041 -0.3689852 ]]


In [69]:
# to double check if we have done it correctly 

print("Mean of 'a'",centered_mean_a.mean(0))
print("Mean of 'b'",centered_mean_b.mean(0))

Mean of 'a' 0.0
Mean of 'b' [-0.0634041   0.20738275 -0.14397865]


In [70]:
a = np.linspace(1,5,50)
b = np.linspace(1,5,50)
c = np.sin(a) **10 + np.cos(10+b)*np.cos(b) 
print(c)

[ 0.18037951  0.3276378   0.49166266  0.66132536  0.81841024  0.94053573
  1.00607242  0.99965371  0.91647373  0.76387392  0.5596446   0.3276342
  0.09217674 -0.12685707 -0.31698955 -0.47353698 -0.59791653 -0.69490734
 -0.77000616 -0.82765831 -0.87058983 -0.899998   -0.91614826 -0.91897889
 -0.90850903 -0.88503285 -0.84917608 -0.80189243 -0.74443946 -0.67834492
 -0.60536117 -0.5273859  -0.44628967 -0.3635662  -0.27976647 -0.19382629
 -0.10260339 -0.00107914  0.11639793  0.25380718  0.41061646  0.57942355
  0.74523702  0.88717891  0.982563    1.01233441  0.96617827  0.84555996
  0.66361623  0.44192559]


### Comparision Operators Universal Functions

In [71]:
a = np.array([1,2,3,4,5,6])

print(a,'\n')
print("Numbers greater than 3 in the array-",a>3) # This gives the result in boolean 
                                                  # The array = [   1,    2,      3,    4,        5,   6]
                                                  # Hence        False ,False , False, True , True ,True    
                                                  #               1<3,     2<3,   3<3,  4>3,   5>3 , 6>3

[1 2 3 4 5 6] 

Numbers greater than 3 in the array- [False False False  True  True  True]


In [72]:
print("Numbers less than 3 in the array-",a<3)    # This gives the result in boolean 
                                                  # The array = [   1,     2,      3,      4,     5,   6]
                                                  # Hence        True , True ,  False, False , False ,False    
                                                  #               1<3,     2<3,   3<3,  4>3,   5>3 , 6>3

Numbers less than 3 in the array- [ True  True False False False False]


In [74]:
print("Numbers less than equal to 3 in the array -",a<=3) # This gives the result in boolean 
                                                          # The array = [   1,     2,        3,       4,     5,   6]
                                                          # Hence        True , True ,    True, False , False ,False    
                                                          #               1<=3,     2<=3,   3<=3,  4>=3,   5>=3 , 6>=3

Numbers less than equal to 3 in the array - [ True  True  True False False False]


In [75]:
print("Numbers greater than equal to 3 in the array -",a>=3)   # This gives the result in boolean 
                                                               # The array = [   1,     2,      3,      4,     5,    6]
                                                               # Hence        False ,False , False,  True ,  True , True    
                                                               #               1<3,     2<3,   3>=3,  4>=3,   5>=3 , 6>=3
            

Numbers greater than equal to 3 in the array - [False False  True  True  True  True]


In [76]:
print("Numbers not equal to 3 in the array -",a!=3)            # This gives the result in boolean 
                                                               # The array = [   1,     2,      3,      4,     5,    6]
                                                               # Hence        True ,  True , False,  True ,  True , True    
                                                               #               1!=3,   2!=3,   3==3,  4!=3,   5!=3 , 6!=3

Numbers not equal to 3 in the array - [ True  True False  True  True  True]


In [77]:
print("Number equal to 3 -",a==3)                              # This gives the result in boolean 
                                                               # The array = [   1,     2,      3,      4,     5,       6]
                                                               # Hence        False ,  False , True,  False ,  False , False    
                                                               #               1!=3,   2!=3,   3==3,  4!=3,   5!=3 , 6!=3

Number equal to 3 - [False False  True False False False]


In [81]:
print(a*2==a**2)                                               # This gives the result in boolean 
                                                               # The array = [   1,     2,      3,      4,     5,       6]
                                                               # According to expression
                                                               #             [ 1*2 == 1**2,  2*2 == 2**2,  3*2==3**2, 4*2 == 4**2,  5*2 == 5**2,  6*2==6**2]
                                                               #             [2!=1,            4 == 4,       6!= 9,       8!=16,    10 != 25,      12!= 36]
                                                               # Hence        False,            True,        False,       False,       False,       False   
                                                               

[False  True False False False False]


In [84]:
b = np.random.random((4,3))
print(b,'\n')
print("Numbers greater than 5-\n", b>0.5)    # If the condition b>0.5 satisfies then it will be replaced by the boolean - True 

[[0.13318673 0.98998394 0.10740083]
 [0.88199378 0.86457564 0.35248614]
 [0.31901537 0.80421083 0.92153252]
 [0.94779818 0.47399159 0.39615456]] 

Numbers greater than 5-
 [[False  True False]
 [ True  True False]
 [False  True  True]
 [ True False False]]


In [87]:
b = np.random.randint(1,10,size=(4,3))
b

array([[6, 2, 7],
       [8, 8, 8],
       [5, 9, 2],
       [9, 6, 3]])

In [90]:
np.count_nonzero(b) # Gives the non-zero elements present in the array

12

In [92]:
print(np.count_nonzero(b<3)) # Gives the non-zero elements which are less than 3

2

In [94]:
print(np.count_nonzero(b>100)) # Gives the non-zero elements which are greater than 100

0


In [95]:
np.sum(b) # Gives the sum of all the values of the array 

73

In [98]:
print(b)
print(np.sum(b<4)) # There are 3 values that are less than 4
                   # In this case values that are less than 4 are equated as 1 and values that are greater than or equal to 4 are equated to 0

[[6 2 7]
 [8 8 8]
 [5 9 2]
 [9 6 3]]
3


In [99]:
print(b)
print("Number of values in rows that are greater than 4 -",np.sum(b>4,axis=1)) # Gives the number of values in a row that are greater than 4 
                                                                               # In the first row there are 2 values 
                                                                               # In the second row there are 3 values
                                                                               # In the third row there are 2 values 
                                                                               # In the fourth row there are 2 values
                                                                               # So the result will be [2 3 2 2]
                                                                                
print("Number of values in columns that are greater than 4 -",np.sum(b>4,axis=0))  # Gives the number of values in a column that are greater than 4 
                                                                                   # In the first row there are 4 values 
                                                                                   # In the second row there are 3 values
                                                                                   # In the third row there are 2 values 
                                                                                   # So the result will be [4 3 2]

[[6 2 7]
 [8 8 8]
 [5 9 2]
 [9 6 3]]
Number of values in rows that are greater than 4 - [2 3 2 2]
Number of values in columns that are greater than 4 - [4 3 2]


In [101]:
print(b)
print("Number of values in rows that are greater than 4 -",np.count_nonzero(b>4,axis=1))

[[6 2 7]
 [8 8 8]
 [5 9 2]
 [9 6 3]]
Number of values in rows that are greater than 4 - [2 3 2 2]


In [103]:
a = np.ones((4,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Counting entries 

In [105]:
# np.any() --> If there is atleast 1 true value then the result is considered as true 

print(np.any(a==1)) # This checks whether any one value in the array is equal to 1. 
                    #If yes, it prints true else it prints false
                    # Here there is atleast one value of '1' so it prints true
    
print(np.any(a>1))  # This checks whether any one value in the array is greater than 1.
                    # If yes, it prints true else it prints false 
                    # Here there are no values of 1 that are greater than that so it prints false 

True
False


In [108]:
print(b)

print(np.any(b>8)) # Checks if there is any one value in the array that is greater than 8
                  # If yes, then prints true else false 
                  # Here there is one value 9 that is greater than 8 so it gives the result as true 
        
print(np.any(b>8,axis=1))   # Checks if there is any one value in the row that is greater than 8 
                            # If yes, then it prints true else it prints false 
                            # Here the first row has [false false false ] --> [false]
                            # Here the second row has [false false false ]--> [false]
                            # Here the third row has [false true false ] --> [true]
                            # Here the fourth row has [true false false ] --> [true]
                            # Hence the answer is [false false true true]


print(np.any(b>8,axis=0))   # Checks if there is any one value in the column that is greater than 8 
                            # If yes, then it prints true else it prints false 
                            # Here the first column has [false false false true ] --> [true]
                            # Here the second column has [false false true false ]--> [false]
                            # Here the third column has [false false false false ] --> [false]
                            # Hence the answer is  [true true false ] 

[[6 2 7]
 [8 8 8]
 [5 9 2]
 [9 6 3]]
True
[False False  True  True]
[ True  True False]


In [109]:
a = np.random.randint(1,6,size=(3,4))
a

array([[3, 4, 2, 4],
       [4, 5, 2, 2],
       [2, 5, 5, 4]])

In [110]:
# np.all() --> if there is any one value false then the result is considered as false 

print(np.all(a>3))  # This checks if there are values that are greater than 3
                    # In the first row [false true false true]  -> [false]
                    # In the second row [ true true false false ] -> [false]
                    # In the third row [false true true true] -> [false]
                    # Therefore the result we get is [false]

False

In [112]:
print(a)
print(np.all(a<10)) # This checks if there are values that are less than 10
                    # In the first row [true true true true]  -> [true]
                    # In the second row [ true true true true ] -> [true]
                    # In the third row [true true true true] -> [true]
                    # Therefore the result we get is [true]  

[[3 4 2 4]
 [4 5 2 2]
 [2 5 5 4]]
True


In [114]:
print(np.all(a<6,axis=0))   # This checks if there are values that are less than 10
                            # In the first row [true true true true]  -> [true]
                            # In the second row [ true true true true ] -> [true]
                            # In the third row [true true true true] -> [true]
                            # In the fourth row [true true true true] -> [true]
                            # Therefore the result we get is [true  true  true true] 

print(np.all(a==2,axis=1))  # This checks if there are values that are equal 1
                            # In the first row [false false true]  -> [false]
                            # In the second row [false false false] -> [false]
                            # In the third row [true true false] -> [false]
                            # Therefore the result we get is [false false false] 

[ True  True  True  True]
[False False False]


### Boolean Operators

In [123]:
a = np.random.random((3,4))

print(a)

print('\n',((a>0.5)&(a<1))) # The output of this line will help you understand which are true and which are false based on the condition provided 

print('\n',np.sum(a>0.5)& np.sum(a<1)) # This gives the result of values that are both greater than 0.5 and less than 1 

print('\n',np.sum(a>0.5)& np.sum(a<1)) # this also gives the same output

[[0.46147952 0.42350158 0.08800287 0.81545294]
 [0.81640652 0.41590406 0.2071232  0.7080092 ]
 [0.96138641 0.2140533  0.0304327  0.81328881]]

 [[False False False  True]
 [ True False False  True]
 [ True False False  True]]

 4

 4


In [122]:
print(a)

print('\n',((a>0.6)|(a==0.11513))) # The output of this line will help you in understanding why we are getting 4 values 

print('\n',np.sum(a>0.6)|np.sum(a==0.11513)) # This gives the output if any one value is true 

print('\n',np.sum(a>0.6) or np.sum(a==0.11513)) # This also gives the same output 

[[0.75285571 0.62685094 0.22748269 0.53541862]
 [0.16977719 0.49143682 0.46246878 0.21499383]
 [0.58219109 0.67212254 0.11513    0.85447859]]

 [[ True  True False False]
 [False False False False]
 [False  True False  True]]

 4

 4


In [131]:
print(a)

print('\n',~(a>0.5)) # this shows how the output is being analysed 

print('\n',np.sum (~(a>0.5)) ) # This gives all the values that are not greater than 0.5

[[0.46147952 0.42350158 0.08800287 0.81545294]
 [0.81640652 0.41590406 0.2071232  0.7080092 ]
 [0.96138641 0.2140533  0.0304327  0.81328881]]

 [[ True  True  True False]
 [False  True  True False]
 [False  True  True False]]

 7


### Boolean Array as Masks

In [133]:
x = np.random.randint(0,6,size=(4,4))
x

array([[0, 5, 0, 2],
       [4, 2, 4, 3],
       [5, 0, 4, 4],
       [0, 0, 0, 0]])

In [137]:
print(x<2) # This gives the result of all the values in boolean format that are less than 2

print('\n',x[x<2])  # This gives the result in 1D array with the values that are less than 2
                    # There are 7 values that are less than 2
print('\n',np.sum(x<2))

[[ True False  True False]
 [False False False False]
 [False  True False False]
 [ True  True  True  True]]

 [0 0 0 0 0 0 0]

 7


### Fancy Indexing

In [145]:
a = np.random.randint(1,100,size=10)
a

array([79, 44, 32, 17, 73, 42, 23,  3, 92, 40])

In [146]:
# Now we can access multiple rows 

print([a[3],a[1],a[9]]) # This gives the element in the 3rd index , 1st index, 9th index of the array

[17, 44, 40]


In [147]:
indexes = [3, 7, 1] # We are storing a lists of numbers 
a[3]                # by using the indexes values we are printing the value from the array 'a'

17

In [148]:
print(a[indexes])   # values in indexes - 3 , 7 , 1 
                    # a[3] --> 17 , a[7] --> 3, a[1] --> 44 

[17  3 44]


In [171]:
b = np.random.randint(1,100,size = (3,3))
b

array([[67, 60, 59],
       [47, 93, 32],
       [62, 94, 23]])

In [172]:
print(b[1]) # Gives the second row in the array 'b'
print(b[1,2]) # Gives the value present at second row and the third column of the array 
print([b[1,2],b[1,1],b[0,1]]) # Gives multiple values 

[47 93 32]
32
[32, 93, 60]


In [178]:
ind = [0,1]   

print(b,'\n')     # Here we get the values of array 'b'
print(b[ind],'\n') # Here we are getting the row 0 and row 1 of the array 'b'
 

[[67 60 59]
 [47 93 32]
 [62 94 23]] 

[[67 60 59]
 [47 93 32]] 

[[67 60 59]]


In [179]:
# The important thing to note here is that shape of results reflects the shape of the index arrays 

# Accessing values from 2D array 

b_rows= [0,1]
b_columns = [0,1]
print(b[b_rows, b_columns]) # You can notice that first value is a combination of b[0,0] and the secind value is a combination of b[1,1]

[67 93]


### Combined Indexing

In [192]:
x = np.arange(12).reshape([3,4]) 
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [193]:
print(x[2,[0,1,2]]) # Here in this code [2,[0,1,2]]
                    # the 2 means the 3rd row is selected as indexing starts from 0 
                    # then [0,1,2] are the index values of each element in row 3 [8, 9, 10]

[ 8  9 10]


In [194]:
print(x[1:,[2,0,2]])    # Here in this code we are using slicing 
                        # 1: states that the 2nd row upto the final row is selected 
                        # [2,0,2] selects values at index 2 , 0
                        # Values at row 2 at index 2,0,2 --> 6  4  6
                        # Values at row 3 at index 2,0,2 --> 10 8  10

[[ 6  4  6]
 [10  8 10]]


In [217]:
print(x,'\n')
print(x.shape,'\n')
row = np.array([0,1,2])
print(row,'\n')
print(row.shape,'\n')

mask = np.array([0,1,0,1],dtype = bool)
print(mask)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

(3, 4) 

[0 1 2] 

(3,) 

[False  True False  True]


In [218]:
print(row[:,np.newaxis],'\n')

print(x[row[:,np.newaxis],mask],'\n')

[[0]
 [1]
 [2]] 

[[ 1  3]
 [ 5  7]
 [ 9 11]] 



### Modifying Values using Fancy Indexing

In [222]:
x = np.arange(10)   # We are creating an array of size 10
print(x)
i = np.array([2,8,1,4]) # We are creating an array having values [2,8,1,4]
print(i)
print(x[i])   # We are using the values in array 'i' as index and x as variable

[0 1 2 3 4 5 6 7 8 9]
[2 8 1 4]
[2 8 1 4]


In [224]:
x[i] = 999  # This modifies the values at index value 2,8,1,4 of the array x 
            # array i consists of [2,8,1,4]
            # The values of x[2], x[8],x[1],x[4] are modified to 999

print(x[i])   
print(x)

[999 999 999 999]
[  0 999 999   3 999   5   6   7 999   9]


In [225]:
x[i] -= 10  # This code will take the value 999 and subtract 10 from it and store it in x[i]
            # x[i] = x[i] - 10 
            # x[2]= x[2] - 10    x[8]= x[8] - 10   x[1]= x[1] - 10   x[4]= x[4] - 10        
            # x[2] = 999 - 10    x[8] = 999 - 10   x[1] = 999 - 10   x[4] = 999 - 10
            # x[2] = 989         x[8] = 989        x[1] = 989        x[4] = 989      
print(x)

[  0 989 989   3 989   5   6   7 989   9]


### at()

In [226]:
x = np.zeros(10)  # creates an array of zeros 
print(x)
print(i) 
np.add.at(x,i,1)   # adds the value of variable x present at index i to 1 
                   # x[2], x[8], x[1], x[4]
                   #   1,  1 ,    1,   1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2 8 1 4]
[0. 1. 1. 0. 1. 0. 0. 0. 1. 0.]
