 ## Numpy_Basics_3   
--> Universal Functions      
--> Arthematic Opreations     
    >> Another way of using Arthematic operators    
--> Absolute Value Functions      
--> Trignometric Functions    
--> Inverse Trignometric Functions    
--> Exponential Functions  
--> Logarithm Functions 
--> Specialized versions  
--> Specifying Outputs [A method of saving memory]  
--> Aggregates  
    >> Reduce  
    >> Accumulate  
    >> Outer  
--> Summing the values in array  
--> Min Max Functions  
--> Axis  

In [ ]:
import numpy as np

### Universal Functions

In [2]:
# Universal Functions -- Ufuncs
# They are a core feature that allows element-wise operations to be performed on arrays in a very efficient way

a = np.arange(5)
b = np.arange(1,6)
print(a,'\n\n',b)

[0 1 2 3 4] 

 [1 2 3 4 5]


In [3]:
a/b   # 0/1 = 0 ,  1/2 = 0.5 ,  2/3 = 0.66 ,  3/4 = 0.75 ,  4/5 = 0.8

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [4]:
x = np.arange(8).reshape((4,2))
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [5]:
x ** 2  # This gives the square of each number present in the array 
        # 0 ** 2 = 0     1 ** 2 = 1
        # 2 ** 2 = 4     3 ** 2 = 9
        # 4 ** 2 = 16    5 ** 2 = 25
        # 6 ** 2 = 36    7 ** 2 = 49
        

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49]])

### Arthematic opreations 

In [7]:
# Lets do some arthematic operations on arrays 
ar1 = np.arange(10)
print("Array -",ar1,'\n\n')
print("Result of Array after Addition -",ar1+2,'\n\n')
print("Result of Array after Subtraction-",ar1-4,'\n\n')
print("Result of Array after Multiplication -",ar1*2,'\n\n')
print("Result of Array after Power -",ar1**3,'\n\n')
print("Result of Array after Division -",ar1/5,'\n\n')
print("Result of Array after Floor Division -",ar1//2,'\n\n')
print("Result of Array after Modulus-[ Gives the Remainder ] -",ar1%3,'\n\n')



Array - [0 1 2 3 4 5 6 7 8 9] 


Result of Array after Addition - [ 2  3  4  5  6  7  8  9 10 11] 


Result of Array after Subtraction- [-4 -3 -2 -1  0  1  2  3  4  5] 


Result of Array after Multiplication - [ 0  2  4  6  8 10 12 14 16 18] 


Result of Array after Power - [  0   1   8  27  64 125 216 343 512 729] 


Result of Array after Division - [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8] 


Result of Array after Floor Division - [0 0 1 1 2 2 3 3 4 4] 


Result of Array after Modulus-[ Gives the Remainder ] - [0 1 2 0 1 2 0 1 2 0] 




In [11]:
ar1 = np.arange(10).reshape((5,2))
print("Array -\n",ar1,'\n\n')
print("Result of Array after Addition -\n",ar1+2,'\n\n')
print("Result of Array after Subtraction-\n",ar1-4,'\n\n')
print("Result of Array after Multiplication -\n",ar1*2,'\n\n')
print("Result of Array after Power -\n",ar1**3,'\n\n')
print("Result of Array after Division -\n",ar1/5,'\n\n')
print("Result of Array after Floor Division -\n",ar1//2,'\n\n')
print("Result of Array after Modulus-[ Gives the Remainder ] -\n",ar1%3,'\n\n')

Array -
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 


Result of Array after Addition -
 [[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 


Result of Array after Subtraction-
 [[-4 -3]
 [-2 -1]
 [ 0  1]
 [ 2  3]
 [ 4  5]] 


Result of Array after Multiplication -
 [[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]] 


Result of Array after Power -
 [[  0   1]
 [  8  27]
 [ 64 125]
 [216 343]
 [512 729]] 


Result of Array after Division -
 [[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]
 [1.2 1.4]
 [1.6 1.8]] 


Result of Array after Floor Division -
 [[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]] 


Result of Array after Modulus-[ Gives the Remainder ] -
 [[0 1]
 [2 0]
 [1 2]
 [0 1]
 [2 0]] 




In [15]:
# You can even provide a expression 

print("Result after Mathematical Expression -\n", (ar1**2)+2)

Result after Mathematical Expression -
 [[ 2  3]
 [ 6 11]
 [18 27]
 [38 51]
 [66 83]]


### Another way of using Arthematic operators 

In [16]:
# You can use np.add() instead of a ' + ' 
# You can use np.subtract() instead of a ' - ' 
# You can use np.negative() instead of a ' - ' here you convert the positive values into negatives and negative values to positive 
# You can use np.multiply() instead of a ' * ' 
# You can use np.divide() instead of a ' / '
# You can use np.floor_divide() instead of a ' // ' 
# You can use np.power() instead of a ' ** ' 
# You can use np.mod() instead of a ' % ' 

In [18]:
print("Array -\n",ar1,'\n\n')
print("Result of Array after Addition -\n",np.add(ar1,3),'\n\n')
print("Result of Array after Subtraction-\n",np.subtract(ar1,2),'\n\n')
print("Result of Array after Multiplication -\n",np.multiply(ar1,4),'\n\n')
print("Result of Array after Power -\n",np.power(ar1,8),'\n\n')
print("Result of Array after Division -\n",np.divide(ar1,2),'\n\n')
print("Result of Array after Floor Division -\n",np.floor_divide(ar1,9),'\n\n')
print("Result of Array after Modulus-[ Gives the Remainder ] -\n",np.mod(ar1,5),'\n\n')

Array -
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 


Result of Array after Addition -
 [[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 


Result of Array after Subtraction-
 [[-2 -1]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]] 


Result of Array after Multiplication -
 [[ 0  4]
 [ 8 12]
 [16 20]
 [24 28]
 [32 36]] 


Result of Array after Power -
 [[       0        1]
 [     256     6561]
 [   65536   390625]
 [ 1679616  5764801]
 [16777216 43046721]] 


Result of Array after Division -
 [[0.  0.5]
 [1.  1.5]
 [2.  2.5]
 [3.  3.5]
 [4.  4.5]] 


Result of Array after Floor Division -
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]] 


Result of Array after Modulus-[ Gives the Remainder ] -
 [[0 1]
 [2 3]
 [4 0]
 [1 2]
 [3 4]] 




### Absolute Value Functions

In [24]:
# Aboslute value 
# Syntax - np.abs() or np.absolute()

ar = np.array([-1,-2,-100,0,1,100])
ar

array([  -1,   -2, -100,    0,    1,  100])

In [25]:
abs(ar)

array([  1,   2, 100,   0,   1, 100])

In [27]:
print('Array -',ar,'\n')
print("Result of Array using np.abs()-",np.abs(ar),'\n')
print("Result of Array using np.absolute()-",np.absolute(ar),'\n')

Array - [  -1   -2 -100    0    1  100] 

Result of Array using np.abs()- [  1   2 100   0   1 100] 

Result of Array using np.absolute()- [  1   2 100   0   1 100] 



In [29]:
# absolute value can handle complex numbers [ 2+3j,1+4j ]
# The aboslute value of a complex number returns the magnitude of two numbers 
# Ex -  2 + 3j  -->    sqrt( (2)** 2  + (3) ** 2 )  -->  sqrt( 4 + 9)  -->  sqrt( 13 ) --> 3.60

np.abs(2+3j)

3.605551275463989

### Trignometric Functions

In [47]:
Theta = np.array([0,30,45,60,90])
Theta

array([ 0, 30, 45, 60, 90])

In [48]:
print("Theta -", Theta)
print(" Sin values for the given Thetha value- ",np.sin(Theta))
print(" Cos values for the given Thetha value- ",np.cos(Theta))
print(" Tan values for the given Thetha value-",np.tan(Theta))

# The values are computed to within machine precision, which is why values that should be zero do not always hit exactly zero.

Theta - [ 0 30 45 60 90]
 Sin values for the given Thetha value-  [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
 Cos values for the given Thetha value-  [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
 Tan values for the given Thetha value- [ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [50]:
# Now if you want the values of the trignometric functions you learned in your schooling 

theta = np.array([0,30,45,60,90])
theta = np.radians(theta)
theta

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [60]:
# you won't be getting values like 1/2 or 1/sqrt(2).
# Instead you will be getting the decimal values for that data 

print("Theta -", theta)
print(" Sin values for the given Thetha value- ",np.sin(theta))
print(" Cos values for the given Thetha value- ",np.cos(theta))
print(" Tan values for the given Thetha value-",np.tan(theta))

Theta - [-0.01745329  0.          0.01745329]
 Sin values for the given Thetha value-  [-0.01745241  0.          0.01745241]
 Cos values for the given Thetha value-  [0.9998477 1.        0.9998477]
 Tan values for the given Thetha value- [-0.01745506  0.          0.01745506]


### Inverse Trignometric Functions 

In [61]:
theta = np.array([-1,0,1])
print("Theta -", theta)
print(" Sin values for the given Thetha value- ",np.arcsin(theta))
print(" Cos values for the given Thetha value- ",np.arccos(theta))
print(" Tan values for the given Thetha value-",np.arctan(theta))

# The given values outputs are in radians because the theta value I provided are not in degrees they are in radians 

Theta - [-1  0  1]
 Sin values for the given Thetha value-  [-1.57079633  0.          1.57079633]
 Cos values for the given Thetha value-  [3.14159265 1.57079633 0.        ]
 Tan values for the given Thetha value- [-0.78539816  0.          0.78539816]


In [67]:
theta = np.array([-1,0,1])
theta = np.radians(theta)
print("Theta -", theta)
print(" Sin values for the given Thetha value- ",np.arcsin(theta))
print(" Cos values for the given Thetha value- ",np.arccos(theta))
print(" Tan values for the given Thetha value-",np.arctan(theta))

Theta - [-0.01745329  0.          0.01745329]
 Sin values for the given Thetha value-  [-0.01745418  0.          0.01745418]
 Cos values for the given Thetha value-  [1.58825051 1.57079633 1.55334215]
 Tan values for the given Thetha value- [-0.01745152  0.          0.01745152]


### Exponential Functions

In [69]:
x = np.array([1,2,3,4,5])

print('values =',x)
print('e^x =',np.exp(x)) 
print('2^x =',np.exp2(x)) # 2 is the base and x is the power 
print('3^x =',np.power(3,x)) # 3 is the base and x is the power 

values = [1 2 3 4 5]
e^x = [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
2^x = [ 2.  4.  8. 16. 32.]
3^x = [  3   9  27  81 243]


In [71]:
# The latest version of numpy doesnot contain np.exp3 and values beyond that 
# However we can use the np.power to execute the program

# Syntax for power --> np.pwer(base, exponent)
print('x^4',np.power(x,4))     # The values of  x are [1,    2,   3,   4,  5]
                               #                     [1^4, 2^4, 3^4, 4^4, 5^4]
                               #                     [1  ,  16, 81,   256, 625]
print('5^x',np.power(5,x))

x^4 [  1  16  81 256 625]
5^x [   5   25  125  625 3125]


### Logarithm Functions

In [75]:
# logarithm is defined as what power must be raised to a base to obtain a given number

log_arr= np.array([1,2,3,4,5,6])

print('Log -',log_arr)
print('Log base 2 -',np.log2(log_arr))  # Logarithm has base 2 
print('Log base 10 -',np.log10(log_arr)) # Logarithm has base 10

Log - [1 2 3 4 5 6]
Log base 2 - [0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
Log base 10 - [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125]


### Specialized versions

In [82]:
# expm1 and log1p are designed to handle certain numerical computations more accurately, especially when working with very small values

ar = np.arange(4)
print("Array -",ar,'\n')
print("Array [ exp(x) - 1 ]-",np.expm1(ar),'\n') # expm1 --> uses ( e^x - 1 )
print("Array [ log(1+x) ]-",np.log1p(ar)) # log1p --> uses log(1+x)

Array - [0 1 2 3] 

Array [ exp(x) - 1 ]- [ 0.          1.71828183  6.3890561  19.08553692] 

Array [ log(1+x) ]- [0.         0.69314718 1.09861229 1.38629436]


In [91]:
# to import these universal functions 
from scipy import special 

# Gamma Function 
# The gamma function generalizes the factorial function for real and complex numbers, except for negative integers and zero

x = [0,0.1,0.2,0.3,0.4,1.10]
print("Gamma -",special.gamma(x))

Gamma - [       inf 9.5135077  4.59084371 2.99156899 2.21815954 0.95135077]


In [92]:
# Gamma Ln Function
# It is useful for numerical stability when dealing with very large or small values 

print("ln|gamma -",special.gammaln(x))

ln|gamma - [        inf  2.25271265  1.52406382  1.09579799  0.79667782 -0.04987244]


In [93]:
# Beta Function
# It is symmetric and commonly appears in calculus and probability

print("Beta -",special.beta(x,2))  # [ Gamma(0) * Gamma(2)/ Gamma(0+2) ]

Beta - [       inf 9.09090909 4.16666667 2.56410256 1.78571429 0.43290043]


In [94]:
# Error Function
# The error function is a mathematical function that arises in statistics and the solution of the heat equation

print("Error -",special.erf(x))

Error - [0.         0.11246292 0.22270259 0.32862676 0.42839236 0.88020507]


In [95]:
# Complimentary Error Function 
# The complementary error function is defined as:
# erfc(x)=1−erf(x)

print("Complimentary Error -",special.erfc(x))

Complimentary Error - [1.         0.88753708 0.77729741 0.67137324 0.57160764 0.11979493]


In [96]:
# Inverse Error Function
# The inverse error function, 
# erf(erfinv(x))=x

print("Inverse Error Function -",special.erfinv(x))

Inverse Error Function - [0.         0.08885599 0.17914345 0.27246271 0.37080716        nan]


### Specifying Outputs

In [100]:
x = np.arange(5)
y = np.empty(5) # Gives the data that are present in the memory location ,referred to as garbage values

print(x) # This gives an arra of 5 elements 
print(y) # this gives an array of 5 values 
print(np.multiply(x,10,out=y)) # the values of x are multiplied by 10 and the result is stored in y
print(y) # this prints the updated array 

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]


In [127]:
ar = np.arange(6, dtype='float64').reshape(3,2) # Due to ar_t consisting of float64 values, We set dtype='float64' to dodge errors 
ar_t = np.linspace(2,6,6).reshape(3,2) # The variable ar_t consists of float64 values 

print(ar,'\n')
print(ar_t,'\n')
print(np.add(ar_t,2,out=ar),'\n')
print(ar)

[[0. 1.]
 [2. 3.]
 [4. 5.]] 

[[2.  2.8]
 [3.6 4.4]
 [5.2 6. ]] 

[[4.  4.8]
 [5.6 6.4]
 [7.2 8. ]] 

[[4.  4.8]
 [5.6 6.4]
 [7.2 8. ]]


In [136]:
y = np.ones(10)
print(x)
np.power(2,x,out=y)
print(y[::2])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]


### Aggregates 

#### Reduce is used for just displaying the final result  
####  Accumulate is used  for displaying the step by step results

#### reduce 

In [139]:
a = np.arange(1,5) # Creates values - 1,2,3,4

np.add.reduce(a) # Adds all the values in the array --> 1+2+3+4 -> 10

10

In [141]:
np.subtract.reduce(a) # Subtracts the values in the array --> 1-2-3-4 -> -8

-8

In [142]:
np.multiply.reduce(a) # Multiplies the values in the array --> 1*2*3*4 -> 24

24

In [143]:
np.divide.reduce(a) # Divides the values in the array --> 1/2/3/4 -> 0.0416

0.041666666666666664

#### accumulate

In [144]:
a 

array([1, 2, 3, 4])

In [145]:
                      # a contains -> 1, 2, 3, 4  
np.add.accumulate(a)  # accumulate does the following -->  
                      # 1,       2,        3,    4      Given Array  
                      # 1, 1+2 = 3, 1+2+3= 6,  1+2+3+4= 10    
                      # 1,       3,        6,   10      Final Result   

array([ 1,  3,  6, 10])

In [146]:
                          # a contains -> 1, 2, 3, 4  
np.subtract.accumulate(a) # accumulate does the following -->  
                          # 1,        2,         3,    4        Given Array  
                          # 1, 1-2 = -1, 1-2-3= -4,  1-2-3-4= -8    
                          # 1,       -1,        -4,   -8        Final Result  
 

array([ 1, -1, -4, -8])

In [147]:
                          # a contains -> 1, 2, 3, 4  
np.multiply.accumulate(a) # accumulate does the following -->  
                          # 1,        2,         3,    4        Given Array  
                          # 1,  1*2=  2,  1*2*3= 6,  1*2*3*4= 24  
                          # 1,        2,         6,   24        Final Result  


array([ 1,  2,  6, 24])

### Outer 

In [150]:
# Important Note --> Results of outer are always 2D,even when operating on 1D vectors or scalars, the output will always be 2D  

a = np.arange(4)
b = np.array([0,1,5,6])

print(a,'\n') # gives the values -->  [0,1,2,3]  
print(b,'\n') # gives the values --> [0,1,5,6]  
print('Product of the two arrays -\n',np.outer(a,b))
                                                    # [0,1,2,3] * [0,1,5,6]  
    
                                                    # [0*0, 0*1, 0*5, 0*6]  
                                                    # [1*0, 1*1, 1*5, 1*6]  
                                                    # [2*0, 2*1, 2*5, 2*6]  
                                                    # [3*0, 3*1, 3*5, 3*6]  
                    
                                                    
                                                    # Result:  
                    
                                                    # [0, 0,  0, 0]  
                                                    # [0, 1,  5, 6]  
                                                    # [0, 2, 10, 12]  
                                                    # [0, 3, 15, 18]  

[0 1 2 3] 

[0 1 5 6] 

Product of the two arrays -
 [[ 0  0  0  0]
 [ 0  1  5  6]
 [ 0  2 10 12]
 [ 0  3 15 18]]


In [155]:
print(a,'\n')

print('Result -\n',np.outer(2,a))   # 2 * [0,1,2,3]  
                                    # [2*0, 2*1, 2*2, 2*3]  
                                    # [0,2,4,6]  

[0 1 2 3] 

Result -
 [[0 2 4 6]]


In [159]:
a1 = np.arange(4).reshape(2,2) # gives a 2x2 array   
a2 = np.arange(6).reshape(2,3) # gives a 2x3 array  

print(a1,'\n') 
print(a2,'\n') 
print('Result-\n',np.outer(a1,a2)) 
                                    # [0, 1]    [0, 1, 2]   =  [0*0, 0*1, 0*2, 0*3, 0*4, 0*5]  =  [0, 0, 0, 0, 0, 0]  
                                    # [2, 3]    [3, 4, 5]      [1*0, 1*1, 1*2, 1*3, 1*4, 1*5]     [0, 1, 2, 3, 4, 5]  
                                    #                          [2*0, 2*1, 2*2, 2*3, 2*4, 2*5]     [0, 2, 4, 6, 8, 10]  
                                    #                          [3*0, 3*1, 3*2, 3*3, 3*4, 3*5]     [0, 3, 6, 9, 12, 15]  
                                   

[[0 1]
 [2 3]] 

[[0 1 2]
 [3 4 5]] 

Result-
 [[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]]


### Summing the values in array 

In [160]:
a = np.random.random(100)
print(a,'\n')
print("sum -",np.sum(a))

[0.71360005 0.39067592 0.97287567 0.19993285 0.664969   0.24402069
 0.54050872 0.85658583 0.21564547 0.05922755 0.77128259 0.91261337
 0.69128461 0.8959721  0.95108445 0.98839134 0.69107051 0.29989744
 0.79353557 0.83892709 0.12563778 0.17263179 0.79960965 0.90966015
 0.5966897  0.79350659 0.00563492 0.0250861  0.73088477 0.1571108
 0.66666721 0.44283163 0.56162919 0.13003239 0.48007732 0.83126785
 0.16809463 0.27920502 0.14523362 0.25182031 0.37699676 0.58880298
 0.7593018  0.68910487 0.77915147 0.23386236 0.55882224 0.55154362
 0.40296714 0.4427947  0.90550851 0.99266887 0.58126475 0.59694297
 0.28797117 0.96090451 0.79730717 0.20970436 0.12443042 0.57711719
 0.63827933 0.34983851 0.19497233 0.20163962 0.00395377 0.16715437
 0.9885742  0.93192104 0.80245695 0.14931381 0.26570977 0.71161659
 0.98111557 0.71684897 0.07710191 0.91784213 0.80712246 0.27648015
 0.83883646 0.10143431 0.90611849 0.0906489  0.3554526  0.76745648
 0.39955689 0.63839139 0.50596174 0.21789829 0.1285954  0.50726

### Min Max Functions 

In [162]:
a = np.random.random(1000)
print('Maximum value in the array- ',np.max(a)) # Gives the maximum value present in the array 
print('Minimum value in the array- ',np.min(a)) # Gives the minimum value present in the array 

Maximum value in the array-  0.9998166723104871
Minimum value in the array-  0.0007199700525335473


### axis

#### axis= 0 --> Does column-wise operations   
#### axis= 1 --> Does row-wise operations   

In [164]:
ar = np.arange(9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [167]:
print('Result of addition of each Columns- ',np.sum(ar,axis=0)) # column values = [ 0+3+6, 1+4+7, 2+5+8 ] --> [9, 12, 15]
                                                                
print("Result of addition of each Rows-",np.sum(ar,axis=1)) # Row values = [0+1+2, 3+4+5, 6+7+8] --> [3, 12, 21]

Result of addition of each Columns-  [ 9 12 15]
Result of addition of each Rows- [ 3 12 21]
