# --- THE BEGINNING OF NUMPY --- #

###### --> how to import numpy 
###### --> how to pip install numpy (if it is not present ) 
###### --> How to create arrays 
###### --> How to use baisc numpy functions 
     --> zeros 
     --> ones
     --> full
     --> arange
     --> linespace
     --> random
          --> random.random
          --> random.randint
          --> random.uniform
     --> eye
     --> ndim
     --> shape
     --> size
     --> dtype
     --> itemsize
     --> nbytes
    
    

In [1]:
import numpy as np   # Here we are importing the numpy library of python and aliasing it as np

In [ ]:
!pip install numpy # This installs numpy on the Jupyter Notebook

In [2]:
# creating an array 
# arrays can be 1D , 2D, 3D 

a = np.array([1,2,3,4,5]) # 1D array
a

array([1, 2, 3, 4, 5])

In [14]:
a = np.array([[1,2,3,4],[3,4,5,6]]) # 2D array
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [17]:
a = np.array([[[1,2,3],[2,3,4]] ,[[1,2,3],[6,12,18]]]) # 3D array
a

array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 1,  2,  3],
        [ 6, 12, 18]]])

In [19]:
a = np.zeros(5)  # creates a 1D array of zeros
a

array([0., 0., 0., 0., 0.])

In [20]:
a = np.zeros((2,4)) # creates a 2D array of zeros
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
a = np.zeros(((3,2,2))) # creates a 3D array of zeros 
a

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [27]:
a = np.ones(3) # creates a 1D array of ones
a

array([1., 1., 1.])

In [28]:
b = np.ones((2,3)) # creates a 2D array of ones
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
c = np.ones((2,3,3)) # creates a 3D array of ones 
c

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
print("Dimensions of a -",a.ndim)
print("Dimensions of b -",b.ndim)
print("Dimensions of c -",c.ndim)

Dimensions of a - 1
Dimensions of b - 2
Dimensions of c - 3


In [32]:
a = np.arange(1,10) # creates a 1D array from 1 inclusive to 10 exclusive
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a = np.linspace(1,6,3) # It creates a 1D array with 3 equally spaced values
a

array([1. , 3.5, 6. ])

In [41]:
a = np.full((2,4), 11 )  # It fills the 2D array consisting of 2 rows and 4 columns with the value 11
a

array([[11, 11, 11, 11],
       [11, 11, 11, 11]])

In [36]:
a = np.random.randint(5, size = 3) # creates a 1D array of size 3 with random integers between 0 inclusive and 5 exclusive
a

array([3, 4, 4])

In [39]:
a = np.random.randint(5, size = (3,5)) # creates a 2D array of 3 rows and 5 columns with random integers between 0 inclusive and 5 exclusive
a

array([[1, 3, 4, 3, 0],
       [0, 2, 1, 3, 1],
       [0, 4, 2, 4, 4]])

In [40]:
# creates a 3D array 2 blocks (or layers),Each block contains 4 rows,Each row contains 2 columns with random integers between 0 inclusive and 10 exclusive
a = np.random.randint(10, size = (2,4,2)) 
a

array([[[5, 5],
        [1, 0],
        [4, 3],
        [8, 9]],

       [[7, 7],
        [8, 5],
        [7, 0],
        [6, 0]]])

In [43]:
uniform_distribution = np.random.random((3,2))  # creates a 3x2 array of uniformly distributed random values between 0 and 1 
uniform_distribution

array([[0.10688436, 0.09478274],
       [0.56480201, 0.68911856],
       [0.4469083 , 0.54951409]])

In [44]:
uniform_dis = np.random.random(2) # creates a 1x2 array of uniformly distributed random values between 0 and 1 
uniform_dis

array([0.66842811, 0.25615329])

In [45]:
# creates a 2x2 array of normally distributed random values with mean- 0 and standard deviation- 1 
normally_distributed = np.random.normal(0,1,(2,2)) 
normally_distributed

array([[ 0.55239127, -0.77969393],
       [-2.72066135, -0.65776981]])

In [46]:
# creates a 3x1 array of normally distributed random values with mean - 1 and standard deviation - 4
normal_dis = np.random.normal(1,4, (3,1)) 
normal_dis

array([[-2.48684526],
       [ 2.22529033],
       [ 4.17714931]])

In [47]:
a = np.eye(2,2) # creates a 2x2 identity matrix
a 

array([[1., 0.],
       [0., 1.]])

In [48]:
a = np.eye(1) # creates a 1x1 identity matrix
a

array([[1.]])

In [49]:
a = np.eye(3) # creates a 3x3 identity matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:

a = np.array([2,3])

print (a)

print(a,'Dimensions-',a.ndim) # Provides the dimensions of array , in this example the array is 1 Dimensional

print(a,'Shape-',a.shape) # Provides the shape of the array as a tuple (indicates the structure of the array) - In the example there are 2 rows and 0 columns so the output is (2,)

print(a,'Size-',a.size) # Provides the total number of elements in the array - In the example there are only 2 values. Hence, the output is 2 

print(a,'Data type-',a.dtype) # Provides the data type of the elements in the array - In the example the data type is int32 - The array stores 32 bit integers 

print(a,'Itemsize-',a.itemsize) # Provides the size in bytes of each element in the array - In the example, each integer occupies 4 bytes [int32 uses 4 bytes per integer]

print(a,'nbytes-',a.nbytes) # Provides The total number of bytes consumed by the array- [ nbytes =  size * itemsize ] -- 2*4 = 8

[2 3]
[2 3] Dimensions- 1
[2 3] Shape- (2,)
[2 3] Size- 2
[2 3] Data type- int32
[2 3] Itemsize- 4
[2 3] nbytes- 8


In [19]:
b = np.array([[1,23,2],[11,22,434]], dtype='float')

print(b)

print('\n')

print('Dimensions-',b.ndim) # Provides the dimensions of array , in this example the array is 2 Dimensional

print('Shape-',b.shape) # Provides the shape of the array as a tuple (indicates the structure of the array) - In the example there are 2 rows and 3 columns so the output is (2,)


print('Size-',b.size) # Provides the total number of elements in the array - In the example there are only 6 values. Hence, the output is 6


print('Data type-',b.dtype) # Provides the data type of the elements in the array - In the example the data type is float64 - The array stores 64 bit float values 


print('Itemsize-',b.itemsize) # Provides the size in bytes of each element in the array - In the example, each integer occupies 8 bytes [float64 uses 8 bytes per integer]


print('nbytes-',b.nbytes) # Provides The total number of bytes consumed by the array- [ nbytes =  size * itemsize ] -- 6*8 = 48


[[  1.  23.   2.]
 [ 11.  22. 434.]]


Dimensions- 2
Shape- (2, 3)
Size- 6
Data type- float64
Itemsize- 8
nbytes- 48
